theme: jekyll-theme-minimal
#theme: minima
title: Welcome to Lexiao's Homepage!
description: I am a Ph.D. Student at Columbia IEOR <br><br><br><br><br><br><br><br><script type='text/javascript' id='clustrmaps' src='//cdn.clustrmaps.com/map_v2.js?cl=ffffff&w=100&t=tt&d=Gdy9sgTo6hTpkNAjMHFIYVC3ZGv6K11WYiFCowwOQJQ&co=2d78ad&cmo=3acc3a&cmn=ff5353&ct=ffffff'></script>
author:
  name: Lexiao Lai
  email: lexiao.lai@columbia.edu
logo: /Lexiao_Lai.JPG
