<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-153662493-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-153662493-1');
</script>
theme: jekyll-theme-cayman
title: Welcome to Lexiao Lai's Homepage!
description: I am a first-year Ph.D. Student at Columbia IEOR
