theme: jekyll-theme-minimal
#theme: minima
title: Welcome to \
Lexiao Lai's Homepage!
description: I am a Ph.D. Student at Columbia IEOR
author:
  name: Lexiao Lai
  email: lexiao.lai@columbia.edu
logo: /Lexiao_Lai.JPG
