theme: jekyll-theme-minimal
#theme: minima
title: Welcome to Lexiao Lai's Homepage!
description: Email: lexiao.lai@columbia.edu
author:
  name: Lexiao Lai
  email: lexiao.lai@columbia.edu
logo: /Lexiao_Lai.JPG
